// frontend/scripts/generate_structured_data.mjs
//
// Writes the schema.org JSON-LD described by `structured_data.mjs` into the
// static HTML pages, between a pair of HTML comment markers.
//
//   node scripts/generate_structured_data.mjs           # write the blocks
//   node scripts/generate_structured_data.mjs --check   # fail if any drifted
//
// `--check` runs first in `npm run check`, which is what keeps ten hand-written
// pages carrying one consistent identity: editing a generated block by hand, or
// editing `structured_data.mjs` and forgetting to regenerate, both fail the
// gate with the file name and a one-line fix.
//
// The script is idempotent — running it twice produces the same bytes — and it
// only ever touches the region between its markers.

import { readFileSync, writeFileSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";
import { PAGES } from "./structured_data.mjs";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const FRONTEND_DIR = resolve(__dirname, "..");

const BEGIN_MARKER =
  "<!-- BEGIN structured data — generated by scripts/generate_structured_data.mjs. Edit scripts/structured_data.mjs and re-run it; hand edits here are overwritten and fail `npm run check`. -->";
const END_MARKER = "<!-- END structured data -->";

// Serialise one page's graph. `<` is escaped because a `</script` sequence
// inside a JSON string would close the surrounding script element early; none
// of the current strings contain one, but the escape costs nothing and removes
// the whole class of problem for whoever edits the copy next.
function serialise(graph) {
  const document = {
    "@context": "https://schema.org",
    "@graph": graph,
  };
  return JSON.stringify(document, null, 2).replace(/</g, "\\u003c");
}

// Match the indentation the file already uses for its head children, so the
// generated block does not stand out in a diff. `<title>` is present in every
// target and is always a direct child of `<head>`.
function headIndent(html) {
  const match = html.match(/^([ \t]*)<title[ >]/m);
  return match ? match[1] : "    ";
}

function buildBlock(graph, indent) {
  const json = serialise(graph)
    .split("\n")
    .map((line) => `${indent}  ${line}`)
    .join("\n");

  return [
    `${indent}${BEGIN_MARKER}`,
    `${indent}<script type="application/ld+json">`,
    json,
    `${indent}</script>`,
    `${indent}${END_MARKER}`,
  ].join("\n");
}

// Replace an existing block, or insert one immediately before `</head>`.
function applyBlock(html, block, file) {
  const beginIndex = html.indexOf(BEGIN_MARKER);
  const endIndex = html.indexOf(END_MARKER);

  if (beginIndex !== -1 && endIndex !== -1) {
    // Re-generating: swap the whole marked region. The slice starts at the
    // beginning of the BEGIN line, so the block supplies its own indentation —
    // trimming it here would make every run produce a different file and the
    // --check gate would fail immediately after a successful write.
    const lineStart = html.lastIndexOf("\n", beginIndex) + 1;
    const lineEnd = endIndex + END_MARKER.length;
    return html.slice(0, lineStart) + block + html.slice(lineEnd);
  }

  if (beginIndex !== -1 || endIndex !== -1) {
    throw new Error(
      `${file}: found one structured-data marker but not the other. Restore both, or delete the partial one and re-run.`
    );
  }

  // First run for this file. Anything already claiming to be JSON-LD would end
  // up competing with the generated graph for the same entities, so refuse
  // rather than silently emit two descriptions of the same app.
  if (html.includes("application/ld+json")) {
    throw new Error(
      `${file}: an unmanaged application/ld+json block is already present. Remove it, then re-run — its content belongs in scripts/structured_data.mjs.`
    );
  }

  const closingHead = html.indexOf("</head>");
  if (closingHead === -1) {
    throw new Error(`${file}: no </head> to insert before.`);
  }

  const lineStart = html.lastIndexOf("\n", closingHead) + 1;
  return `${html.slice(0, lineStart)}${block}\n${html.slice(lineStart)}`;
}

function main() {
  const checkOnly = process.argv.includes("--check");
  const stale = [];
  let written = 0;

  for (const page of PAGES) {
    for (const target of page.targets) {
      const path = resolve(FRONTEND_DIR, target);
      const html = readFileSync(path, "utf8");
      const block = buildBlock(page.graph, headIndent(html));
      const next = applyBlock(html, block, target);

      if (next === html) continue;

      if (checkOnly) {
        stale.push(target);
      } else {
        writeFileSync(path, next, "utf8");
        written += 1;
      }
    }
  }

  if (checkOnly) {
    if (stale.length > 0) {
      console.error(
        `❌ structured data is out of date in ${stale.length} file(s):`
      );
      stale.forEach((file) => console.error(`   - ${file}`));
      console.error("   Run: npm run seo");
      process.exit(1);
    }
    const files = PAGES.reduce((sum, page) => sum + page.targets.length, 0);
    console.log(`✅ structured data current in ${files} files`);
    return;
  }

  console.log(
    written === 0
      ? "✅ structured data already current — nothing to write"
      : `✅ structured data written to ${written} file(s)`
  );
}

main();
